version: '3'

services:

  server:
    container_name: fcgi
    build:
      dockerfile: Part5.Dockerfile
    networks:
    - do5

  frontend:
    container_name: web
    image: nginx
    volumes:
    - ./nginx/nginx_part6.conf:/etc/nginx/nginx.conf
    ports:
    - 80:8080
    networks:
    - do5

networks:
  do5:
    driver: bridge